## 00. PyTorch Fundamentals
Get the code: https://github.com/mrdbourke/pytorch-deep-learning

See the book: https://www.learnpytorch.io/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## **Introduction to Tensors**

### **Creating Tensors**

PyTorch tensors are created using `torch.tensor()`

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
 scalar.ndim

0

In [ ]:
# Get tensor back as PyToroch
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### **Random tensors**

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those ranom numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers - > look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5357, 0.0360, 0.7525, 0.6234],
        [0.9867, 0.2170, 0.0574, 0.8037],
        [0.0169, 0.0795, 0.7562, 0.8718]])

In [ ]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### **Zeros and ones**

In [ ]:
# Crate a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### **Creating a range of tensors and tensors-like**

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### **Tensor datatypes**

Note: Tensor datatypes is one of the 3 big errors we'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right space
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                                device=None, # What device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
float_16_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### **Getting information from tensors**

1. Tensors not right datatype - to do get datatypr from a tensor, can use `tensort.dtype`
2. tensors not righ t space - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get deivce from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7177, 0.5235, 0.5915, 0.4005],
        [0.8375, 0.7577, 0.9547, 0.4126],
        [0.5708, 0.6484, 0.7935, 0.3378]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on {some_tensor.device}")

tensor([[0.7177, 0.5235, 0.5915, 0.4005],
        [0.8375, 0.7577, 0.9547, 0.4126],
        [0.5708, 0.6484, 0.7935, 0.3378]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on cpu


### Manipulating Tensors (tensor operations)

Tensor operatiions include:
* Adition
* Substruction
* Multiplication (elemen-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply
tensor*10

tensor([10, 20, 30])

In [ ]:
# Substract
tensor-10

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multoplication
2. Matrix multiplication (DOT product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`


In [ ]:
# ELement wise multiplication
print(tensor,'*',tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]+tensor[i]
print(value)

tensor(12)
CPU times: user 1.04 ms, sys: 0 ns, total: 1.04 ms
Wall time: 2.06 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 303 µs, sys: 0 ns, total: 303 µs
Wall time: 217 µs


tensor(14)

### One of the most commant errors in deep learning: shape errors

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B,tensor_B.shape, tensor_B.T, tensor_B.T.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index which is minumum value
x.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has the minimum value with argmax() -> returns index which is maximum value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping -reshapes an unpur tensor to a defined shape
* View -Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking -combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze -removes all `1` dimensions from a tensor
* Unsqueeze -add a `1` dimension to a target tensor
* Permute -Return a view of the input with dimensions permuted (swapped) in a cartain way

In [ ]:
 x= torch.arange(1,10)
 x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add extra dimension
x_reshaped = x.reshape(9,1)  # size ile uyumlu olmasi gerekir 3x3 yapariz ama 5x2 yapamayiz
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
# View
z=x.view(9,1)
z,z.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
# z degisirse x de degisir
z[:, 0]=5
z,x

(tensor([[5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5]]),
 tensor([5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [ ]:
# Stack tensors on top
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
print((f"Previous targertt: {x_reshaped}"))
print(f"Previous shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous targertt: tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Previous shape: torch.Size([9, 1])
New tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute()
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
###

### Getting a GPU

1. Easiest - Google Colap
2. Use your own GPU
3. Use cloud computing

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])